# Problem 1 

In [3]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
array = np.array([5, 2, 9, 1, 3])
print(array)
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
sort = np.sort(array)
print(sort)

[5 2 9 1 3]
[1 2 3 5 9]


# Problem 2

In [35]:
import numpy as np
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
array = np.array([10, 15, 30, 45, 60])

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
array1 = np.arange(5, 16)
print(array1)
 
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
array2 = np.arange(50, 101, 5)
print(array2)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
array3 = np.zeros(10)
print(array3)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
array4 = np.ones(10)
print(array4)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
array5 = np.linspace(0, 100, 5)
print(array5)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
array6 = np.random.randint(10, 31, size = 5)
print(array6)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
array7 = np.linspace(-1, 1, 10)
print(array7)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
array8 = np.random.randint(10, 51, 15)
array8 = array8.reshape(3,5)
print(array8)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
satir_toplamlari = np.sum(array8, axis=1)
print(satir_toplamlari)
sutun_toplamlari = np.sum(array8, axis=0)
print(sutun_toplamlari)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
en_buyuk_sayi = array8.max()
print(en_buyuk_sayi)
en_kucuk_sayi = array8.min()
print(en_kucuk_sayi)

ortalama = (en_buyuk_sayi + en_kucuk_sayi) / 2
print(ortalama)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
satir, sutun = np.unravel_index(np.argmax(array8), array8.shape)
print(f"[{satir}][{sutun}]")

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
array9 = np.arange(10,21)
print(array9)
elemanlar = [0,1,2]
print(array9[elemanlar])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(array9[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(array8[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(array8[1][2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
ilk_elemanlar = (array8[0][0] , array8[1][0], array8[2][0])
print(ilk_elemanlar)

# 18- Üretilen matrisin her bir elemanının karesini alınız.
array8_karesi = np.square(array8)
print(array8_karesi)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
array10 = np.random.randint(-50, 51, size=(3, 5))
print(array10)
mask = (array10 > 0)
pozitifler = array10[mask]
print(pozitifler)


[ 5  6  7  8  9 10 11 12 13 14 15]
[ 50  55  60  65  70  75  80  85  90  95 100]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[11 19 17 22 26]
[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
[[16 47 24 18 25]
 [29 14 26 32 35]
 [32 39 38 15 21]]
[130 136 145]
[ 77 100  88  65  81]
47
14
30.5
[0][1]
[10 11 12 13 14 15 16 17 18 19 20]
[10 11 12]
[20 19 18 17 16 15 14 13 12 11 10]
[16 47 24 18 25]
26
(np.int32(16), np.int32(29), np.int32(32))
[[ 256 2209  576  324  625]
 [ 841  196  676 1024 1225]
 [1024 1521 1444  225  441]]
[[  3  43 -18 -44  25]
 [ 42  43 -13  10 -50]
 [-36  40 -16  -7  47]]
[ 3 43 25 42 43 10 40 47]
