# Problem 1

In [7]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matris = np.random.randint(0, 11, 5)
print(matris)
# 3 - matris'in boyutunu öğrenin
print(matris.shape)
# 4 - matris'i yeniden boyutlandırın
print(matris.reshape(5, 1))
# 5 - matris'in boyut sayısını öğrenin
print(matris.ndim)

[9 2 7 1 2]
(5,)
[[9]
 [2]
 [7]
 [1]
 [2]]
1


# Problem 2

In [13]:
import numpy as np
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
tek_sayilar = np.arange(1, 11, 2)
print(tek_sayilar)
# 2 - Oluşturduğunuz matrisi parçalayın
tek_sayilar_parcali = np.array_split(tek_sayilar, 3)
print(tek_sayilar_parcali)
# 3 - Parçalanmış matrisleri birleştirin
tek_sayilar_birlestirilmis = np.concatenate(tek_sayilar_parcali)
print(tek_sayilar_birlestirilmis)

[1 3 5 7 9]
[array([1, 3]), array([5, 7]), array([9])]
[1 3 5 7 9]


# Problem 3

In [25]:
import numpy as np
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
sayilar = np.arange(5, 101, 2)
sayilar2 = np.random.choice(sayilar, size = 10, replace=False)
print(sayilar2)
# 2 - matris'in özelliklerini inceleyin
print("boyut sayısı:" ,sayilar2.ndim)
print("boyut bilgisi", sayilar2.shape) 
print("toplam eleman sayısı:" ,sayilar2.size) 
print("veri tipi" ,sayilar2.dtype) 

[45 33 55 81 87 91 99 57 93 71]
boyut sayısı: 1
boyut bilgisi (10,)
toplam eleman sayısı: 10
veri tipi int64
