In [ ]:
# kurulumu yapmak için:
!pip install numpy
#kurduktan sonra bu code delete ile silip restart ile yenileyeğiz

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.8 MB 4.7 MB/s eta 0:00:03
   ----- ---------------------------------- 1.8/12.8 MB 5.3 MB/s eta 0:00:03
   --------- ------------------------------ 3.1/12.8 MB 5.4 MB/s eta 0:00:02
   ------------- -------------------------- 4.2/12.8 MB 5.3 MB/s eta 0:00:02
   ---------------- ----------------------- 5.2/12.8 MB 5.4 MB/s eta 0:00:02
   ------------------ --------------------- 6.0/12.8 MB 5.1 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.8 MB 4.9 MB/s eta 0:00:02
   ------------------------ --------------- 7.9/12.8 MB 4.8 MB/s eta 0:00:02
   --------------------------- ------------ 8.7/12.8 MB 4.6 MB/s eta 0:00:01
   ------------------------------ --------- 9.7/12.8 MB 4.7 MB/s eta 0:00:01
   --------------------------------- ------ 10.7/12.8 MB 4.7 MB/s eta 0:00:01
   ------------------------------------ --- 11.8/12.8 MB 4.7 MB/s eta 0:00:01
   -


[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
#klasik yöntem (numpy olmadan)

a = [1,2,3,4]
b= [2,3,4,5]
ab = []
for i in range(0, len(a)):
    ab.append(a[i] + b[i])
print(ab)

[3, 5, 7, 9]


In [8]:
#numpy ile 
import numpy as np
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
print(a+b)

[3 5 7 9]


In [ ]:
#reshape fonksiyonu
import numpy as np

x = np.array([1,2,3,4,5,6,7,8,9])
multi = x.reshape(3,3)
print(multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
#shape fonksiyonu
import numpy as np

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
multi = x.reshape(3, 3)
print(multi.shape)
print(x.shape)

(3, 3)
(9,)


In [ ]:
#ndim
import numpy as np

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
multi = x.reshape(3, 3)
print(x.ndim) #tek boyutlu array
print(multi.ndim) #iki boyutlu array

1
2


In [26]:
import numpy as np
x = np.array([1,2,3,4,5])    
y = np.array([6,7,8,9,10])
print(np.concatenate([x, y]))

z = np.array([11,12,13,14,15])
print(np.concatenate([x, y, z]))

a = np.array([[1,2,3],[4,5,6]])
print(np.concatenate([a, a]))

print(np.concatenate([a, a], axis=1))  # sütun bazında birleştirme
print(np.concatenate([a, a], axis=0))  # satır bazında birleştirme

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
n = np.array([1,2,3,99,99,3,2,1])
print(np.split(n, [3,5]))
#0-1-2 alır sonra 3-4 alır ve 5-6-7 alır

a,b,c = np.split(n, [3,5])
print(a)
print(b)
print(c)

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]
[1 2 3]
[99 99]
[3 2 1]


In [ ]:
#vsplit fonksiyonu
import numpy as np
#.arange(16) ile 0'dan 16'ya kadar sayıları oluşturur
n = np.arange(16).reshape(4, 4)
np.vsplit(n, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
# vsplit fonksiyonu
import numpy as np
#.arange(16) ile 0'dan 16'ya kadar sayıları oluşturur
n = np.arange(16).reshape(4, 4)
np.hsplit(n, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
#arange fonksiyonu
import numpy as np
np.arange(3,12,2) 
#3'ten 12'ye kadar 2'şer artarak sayıları oluşturur

array([ 3,  5,  7,  9, 11])

In [ ]:
#zeros fonksiyonu
import numpy as np
np.zeros(5)  
# 5 tane sıfırdan oluşan bir dizi oluşturur

array([0., 0., 0., 0., 0.])

In [33]:
#ones fonksiyonu
import numpy as np
np.ones(5)  
# 5 tane birden oluşan bir dizi oluşturur

array([1., 1., 1., 1., 1.])

In [39]:
import numpy as np
np.linspace(0, 100, 5)
# 0 ile 100 arasında 5 eşit parçaya bölünmüş sayılar oluştur

array([  0.,  25.,  50.,  75., 100.])

In [40]:
import numpy as np
np.random.randint(0,10,3)
# 0 ile 10 arasında 3 adet rastgele tamsayı oluşturur

array([4, 0, 9], dtype=int32)

In [ ]:
import numpy as np
np.random.randint(2,22,5)
# 2 ile 22 arasında 5 adet rastgele tamsayı oluşturur

array([ 2, 11, 16,  8, 14], dtype=int32)

In [43]:
npArray = np.arange(50)
#0'dan 49'a kadar sayıları içeren bir dizi oluşturur
npMulti = npArray.reshape(5,10)
# 5 satır ve 10 sütundan oluşan bir matris oluşturur
print(npMulti.sum(axis = 1))
# her satırın toplamını hesaplar

[ 45 145 245 345 445]


In [5]:
import numpy as np
a = np.random.randint(10,size = 10)
print(a.ndim)
# a.ndim ile dizinin boyut sayısını (ndim) yazdırır
print(a.shape)      
# a.shape ile dizinin boyutlarını (shape) yazdırır
print(a.size)   
# a.size ile dizinin toplam eleman sayısını (size) yazdırır
print(a.dtype) 
# a.dtype ile dizinin veri tipini (dtype) yazdırır

1
(10,)
10
int32


In [ ]:
import numpy as np
v = np.array([8,24,232,12,5,42,55])
print(v)
v.sort()
print(v)

[  8  24 232  12   5  42  55]
[  5   8  12  24  42  55 232]


In [7]:
n = np.random.normal(20,5,(3,3))
print(n)
# normal dağılıma göre 20 ortalama ve 5 standart sapma ile 3x3 boyutunda bir matris oluşturur

[[13.66407658 28.50079778 21.99053444]
 [20.30480767 11.6528527  27.76204473]
 [25.87063823 21.50772641 18.80696012]]


In [8]:
print(np.sort(n, axis=0))
# n matrisini sütun bazında sıralar

[[13.66407658 11.6528527  18.80696012]
 [20.30480767 21.50772641 21.99053444]
 [25.87063823 28.50079778 27.76204473]]


In [9]:
print(np.sort(n, axis = 1))
# n matrisini satır bazında sıralar

[[13.66407658 21.99053444 28.50079778]
 [11.6528527  20.30480767 27.76204473]
 [18.80696012 21.50772641 25.87063823]]


In [ ]:
import numpy as np
a = np.random.randint(10, size=10)
print(a[0]) # a dizisinin ilk elemanını yazdırır
print(a[-1]) # a dizisinin son elemanını yazdırır
a[0] = 100 
print(a)

# 3 satır ve 5 sütundan oluşan rastgele bir matris oluşturur
x = np.random.randint(10, size=(3,5)) 
print(x)
print(x[0, 0]) # x matrisinin ilk satır ve ilk sütun elemanını yazdırır

x[1,2] = 300 #x matrisinin ikinci satır ve beşinci sütun elemanını 300 olarak günceller
print(x)

5
3
[100   5   5   4   9   1   7   5   3   3]
[[5 9 1 0 1]
 [2 9 0 5 8]
 [3 8 3 5 9]]
5
[[  5   9   1   0   1]
 [  2   9 300   5   8]
 [  3   8   3   5   9]]


In [4]:
import numpy as np
a = np.arange(20,30)
print(a)

print(a[0:3]) # a dizisinin ilk üç elemanını yazdırır
print(a[:3])  # a dizisinin ilk üç elemanını yazdırır
print(a[3:])  # a dizisinin dördüncü elemanından sonrasını yazdırır
print(a[3::6])  # a dizisinin dördüncü elemanından başlayarak her altıncı elemanını yazdırır
print(a[::2]) # a dizisinin her ikinci elemanını yazdırır
print(a[::-1]) # a dizisini ters çevirir
print(a[1:8:2]) # a dizisinin ikinci elemanından başlayarak

b = np.random.randint(10, size=(5,5))
print(b)
print(b[:,0]) # b matrisinin tüm satırlarını ve ilk sütununu yazdırır
print(b[0,:]) # b matrisinin ilk satırını ve tüm sütunlarını yazdırır
print(b[0:2,0:3]) # b matrisinin ilk iki satırını ve ilk üç sütununu yazdırır
print(b[::2, ::2]) # b matrisinin her ikinci satırını ve her ikinci sütununu yazdırır

[20 21 22 23 24 25 26 27 28 29]
[20 21 22]
[20 21 22]
[23 24 25 26 27 28 29]
[23 29]
[20 22 24 26 28]
[29 28 27 26 25 24 23 22 21 20]
[21 23 25 27]
[[1 6 7 3 6]
 [6 4 7 6 5]
 [4 5 9 2 8]
 [1 5 2 6 9]
 [4 6 0 7 7]]
[1 6 4 1 4]
[1 6 7 3 6]
[[1 6 7]
 [6 4 7]]
[[1 7 6]
 [4 9 8]
 [4 0 7]]


In [8]:
import numpy as np
b = np.random.randint(10, size=(5,5))
alt_b = b[0:2, 0:3]  # b matrisinin ilk iki satırını ve ilk üç sütununu alır
alt_b

array([[9, 9, 5],
       [8, 7, 1]], dtype=int32)

In [9]:
alt_b[0,0] = 100  # alt_b matrisinin ilk satır ve ilk sütun elemanını 100 olarak günceller
alt_b

array([[100,   9,   5],
       [  8,   7,   1]], dtype=int32)

In [2]:
import numpy as np
v = np.arange(0,30,3) # 0'dan 30'a kadar 3'er artan bir dizi oluşturur
print(v)

yetgen = [1,3,5]
print(v[yetgen]) # v dizisinin 1, 3 ve 5 indekslerindeki elemanlarını yazdırır

n = np.arange(9).reshape(3,3)
satir = np.array([0,1])
sutun = np.array([0,2])
print(n[satir, sutun])  # n matrisinin 0. ve 1. satırlarının 0. ve 2. sütun elemanlarını yazdırır

[ 0  3  6  9 12 15 18 21 24 27]
[ 3  9 15]
[0 5]


In [4]:
v = np.array([1,2,3,4,5])
print(v > 3)  # v dizisindeki elemanların 3'ten büyük olup olmadığını kontrol eder ve True/False değerlerini yazdırır
print(v[v > 3])  # v dizisindeki 3'ten büyük elemanları yazdırır
print(v[v < 3])  # v dizisindeki 3'ten küçük elemanları yazdırır
print(v[v == 3])  # v dizisindeki 3'e eşit elemanları yazdırır
print(v[v != 3])  # v dizisindeki 3'e eşit olmayan elemanları yazdırır
print(v[v >= 3])  # v dizisindeki 3'e eşit veya daha büyük elemanları yazdırır
print(v[v <= 3])  # v dizisindeki 3'e eşit veya daha küçük elemanları yazdırır

[False False False  True  True]
[4 5]
[1 2]
[3]
[1 2 4 5]
[3 4 5]
[1 2 3]


In [ ]:
v = np.array([1,2,3,4,5])
print(v*2) # v dizisini 2 ile çarpar
print(v + 2)  # v dizisine 2 ekler
print(v - 2)  # v dizisinden 2 çıkarır      
print(v / 2)  # v dizisini 2'ye böler
print(v ** 2)  # v dizisinin her elemanını karesini al
print(np.subtract(v, 2))  # v dizisinden 2 çıkarır
print(np.add(v, 2))  # v dizisine 2 ekler   
print(np.multiply(v, 2))  # v dizisini 2 ile çarpar
print(np.divide(v, 2))  # v dizisini 2'ye böler
print(np.power(v, 2))  # v dizisinin her elemanının karesini alır  
print(np.sqrt(v))  # v dizisinin her elemanının karekökünü alır
print(np.exp(v))  # v dizisinin her elemanının e üzeri değerini alır
print(np.mod(v, 2))  # v dizisinin her elemanının 2 ile bölümünden kalanı alır
print(np.abs(v))  # v dizisinin her elemanının mutlak değerini alır
print(np.absolute(v))  # v dizisinin her elemanının mutlak değerini alır
print(np.floor(v))  # v dizisinin her elemanının alt tamsayısını alır
print(np.ceil(v))  # v dizisinin her elemanının üst tamsayısını alır
print(np.round(v))  # v dizisinin her elemanını en yakın tamsayıya yuvarlar
print(np.clip(v, 2, 4))  # v dizisinin her elemanını 2 ile 4 arasında sınırlar  

[ 2  4  6  8 10]
[3 4 5 6 7]
[-1  0  1  2  3]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]
[-1  0  1  2  3]
[3 4 5 6 7]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [10]:
#iki bilinmeyenli denklem çözümü
import numpy as np
A = np.array([[5, 1], [1, 3]])
B = np.array([12, 10])
x = np.linalg.solve(A, B)  # A matrisini ve B vektörünü kullanarak x ve y'yi çözer
print(x)  # x ve y değerlerini yazdırır

[1.85714286 2.71428571]
